REPORT ZPRG_INTERFACE1.

PARAMETERS: PVBELN TYPE VBELN_VA.
PARAMETERS: R1 TYPE C RADIOBUTTON GROUP R1.
PARAMETERS: R2 TYPE C RADIOBUTTON GROUP R1.

DATA : CLASS1 TYPE REF TO ZSUBSALES.
DATA : CLASS2 TYPE REF TO ZSUBBILLING.

INTERFACE ZINTERFACE1.
METHODS DISPLAY IMPORTING PVBELN TYPE VBELN_VA
                EXPORTING PERDAT TYPE ERDAT
                          PERZET TYPE ERZET
                          PERNAM TYPE ERNAM
                          PVBTYP TYPE  VBTYP.
ENDINTERFACE.

CLASS CLASS1 DEFINITION.
PUBLIC SECTION.
INTERFACES ZINTERFACE1.
ENDCLASS.

CLASS CLASS1 IMPLEMENTATION.
  METHOD ZINTERFACE1~DISPLAY.
    SELECT SINGLE ERDAT ERZET ERNAM VBTYP
    FROM VBAK
    INTO ( PERDAT, PERZET, PERNAM, PVBTYP )
    WHERE VBELN = PVBELN.
ENDMETHOD .
ENDCLASS.

CLASS CLASS2 DEFINITION.
PUBLIC SECTION.
INTERFACES ZINTERFACE1.
ENDCLASS.

CLASS CLASS2 IMPLEMENTATION.
  METHOD ZINTERFACE1~DISPLAY.
    SELECT SINGLE ERDAT ERZET ERNAM VBTYP
    FROM VBRK
    INTO ( PERDAT, PERZET, PERNAM, PVBTYP )
    WHERE VBELN = PVBELN.
ENDMETHOD .
ENDCLASS.

START-OF-SELECTION.
DATA : LO_OBJECT1 TYPE REF TO CLASS1.
DATA : LO_OBJECT2 TYPE REF TO CLASS2.

DATA : P_VBELN TYPE  VBELN_VA.
DATA  :P_ERDAT  TYPE ERDAT.
DATA : P_ERZET TYPE ERZET.
DATA : P_ERNAM TYPE ERNAM.
DATA : P_VBTYP TYPE  VBTYP.

IF R1 = 'X'.
CREATE OBJECT  LO_OBJECT1.
LO_OBJECT1->ZINTERFACE1~DISPLAY( EXPORTING PVBELN = P_VBELN
                                   IMPORTING PERDAT =  P_ERDAT
                                             PERZET = P_ERZET
                                             PERNAM = P_ERNAM
                                             PVBTYP = P_VBTYP ).
WRITE: /'sales document details',
      / p_vbeln,
      / p_erdat,
      / p_erzet,
      / p_erNAM,
      / p_vbtyp.
endif.

IF R1 = 'X'.
CREATE OBJECT  LO_OBJECT2.
LO_OBJECT2->ZINTERFACE1~DISPLAY( EXPORTING PVBELN = P_VBELN
                                   IMPORTING PERDAT =  P_ERDAT
                                             PERZET = P_ERZET
                                             PERNAM = P_ERNAM
                                             PVBTYP = P_VBTYP ).
WRITE:
      / p_vbeln,
      / p_erdat,
      / p_erzet,
      / p_ernam,
      / p_vbtyp.
endif.